# linear and angular speed limits for the robot
max_v: 1.33 # m/s
max_w: 5.0 # rad/s
# observation rate fo the robot
frame_rate: 6 # Hz
graph_rate: 0.3333 # Hz

# topic names (modify for different robots/nodes)
vel_teleop_topic: /cmd_vel_mux/input/teleop
vel_navi_topic: /cmd_vel
vel_recovery_topic: /cmd_vel_mux/input/recovery

# optional robot geometry (for reference; not used directly by ROS2 publisher)
wheel_separation: 0.26 # m
wheel_radius: 0.069 # m
